-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 12:46:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`STUDENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENTS` (
  `idStudents` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `AGE` INT NOT NULL,
  `MOBILE NUMBER` VARCHAR(45) NOT NULL,
  `BIRTH DATE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudents`),
  UNIQUE INDEX `idStudents_UNIQUE` (`idStudents` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEES` (
  `idEMPLOYEE` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `AGE` INT NOT NULL,
  `MOBILE NUMBER` VARCHAR(45) NOT NULL,
  `BIRTH DATE` DATETIME NOT NULL,
  `WORKEXPERIENCE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEMPLOYEE`),
  UNIQUE INDEX `idEMPLOYEE_UNIQUE` (`idEMPLOYEE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TEACHERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TEACHERS` (
  `EMPLOYEES_idEMPLOYEE` INT NOT NULL,
  `NUMBER OF SUBORDINATES` INT NOT NULL,
  `NUMBER OF PUBLICATIONS` INT NOT NULL,
  INDEX `fk_TEACHERS_EMPLOYEES1_idx` (`EMPLOYEES_idEMPLOYEE` ASC),
  PRIMARY KEY (`EMPLOYEES_idEMPLOYEE`),
  UNIQUE INDEX `EMPLOYEES_idEMPLOYEE_UNIQUE` (`EMPLOYEES_idEMPLOYEE` ASC),
  CONSTRAINT `fk_TEACHERS_EMPLOYEES1`
    FOREIGN KEY (`EMPLOYEES_idEMPLOYEE`)
    REFERENCES `mydb`.`EMPLOYEES` (`idEMPLOYEE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENTS_HAVE_TEACHERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENTS_HAVE_TEACHERS` (
  `STUDENTS_idStudents` INT NOT NULL,
  `TEACHERS_EMPLOYEES_idEMPLOYEE` INT NOT NULL,
  INDEX `fk_STUDENTS_HAVE_TEACHERS_STUDENTS1_idx` (`STUDENTS_idStudents` ASC),
  INDEX `fk_STUDENTS_HAVE_TEACHERS_TEACHERS1_idx` (`TEACHERS_EMPLOYEES_idEMPLOYEE` ASC),
  CONSTRAINT `fk_STUDENTS_HAVE_TEACHERS_STUDENTS1`
    FOREIGN KEY (`STUDENTS_idStudents`)
    REFERENCES `mydb`.`STUDENTS` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENTS_HAVE_TEACHERS_TEACHERS1`
    FOREIGN KEY (`TEACHERS_EMPLOYEES_idEMPLOYEE`)
    REFERENCES `mydb`.`TEACHERS` (`EMPLOYEES_idEMPLOYEE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ECONOMISTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ECONOMISTS` (
  `EMPLOYEES_idEMPLOYEE` INT NOT NULL,
  `CATEGORY` INT NULL,
  INDEX `fk_ECONOMISTS_EMPLOYEES1_idx` (`EMPLOYEES_idEMPLOYEE` ASC),
  PRIMARY KEY (`EMPLOYEES_idEMPLOYEE`),
  UNIQUE INDEX `EMPLOYEES_idEMPLOYEE_UNIQUE` (`EMPLOYEES_idEMPLOYEE` ASC),
  CONSTRAINT `fk_ECONOMISTS_EMPLOYEES1`
    FOREIGN KEY (`EMPLOYEES_idEMPLOYEE`)
    REFERENCES `mydb`.`EMPLOYEES` (`idEMPLOYEE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
